services:
  postgres:
    image: postgres:16
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: ecommerce-userservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__UserDb: Host=postgres;Port=5432;Database=userdb;Username=postgres;Password=postgres
      Jwt__Secret: 2wF7nL9sQ1xT6mZ4cV8bN3kR5pH2yD0j
      Jwt__Issuer: ECommercePlatform
      Jwt__Audience: ECommercePlatform
      Jwt__ExpiryHours: 24
    ports:
      - "5124:8080"

  productservice:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    container_name: ecommerce-productservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__ProductDb: Host=postgres;Port=5432;Database=productdb;Username=postgres;Password=postgres
    ports:
      - "5212:8080"

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: ecommerce-orderservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__OrderDb: Host=postgres;Port=5432;Database=orderdb;Username=postgres;Password=postgres
    ports:
      - "5313:8080"

  paymentservice:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    container_name: ecommerce-paymentservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__PaymentDb: Host=postgres;Port=5432;Database=paymentdb;Username=postgres;Password=postgres
      Stripe__SecretKey: ${Stripe__SecretKey}
      Stripe__WebhookSecret: ${Stripe__WebhookSecret}
      Stripe__Currency: ${Stripe__Currency}
    ports:
      - "5314:8080"

volumes:
  pgdata:
